# Copyright 2026 Quantova Inc
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "qtv-bft"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
publish = false

[lib]
name = "qtv_bft"

[features]
test-fixtures = []
model = []

[dependencies]
qtv-crypto = { git = "https://github.com/Quantova/Q-Crypto.git", rev = "4abe71e9fa84a6e670e6d5736d7533c3fd10a3ed" }

[dev-dependencies]
qtv-bft = { path = ".", features = ["test-fixtures", "model"] }
