# Copyright 2026 Quantova Inc
# SPDX-License-Identifier: Apache-2.0 OR MIT

[package]
name = "qtv-bft"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 OR MIT"
publish = false

[lib]
name = "qtv_bft"

[features]
test-fixtures = []
model = []

[dependencies]
qtv-crypto = { git = "https://github.com/Quantova/Q-Crypto.git", rev = "80b30f55cc563018b997eea20c6ee48b76424fa9" }

[dev-dependencies]
qtv-bft = { path = ".", features = ["test-fixtures", "model"] }
